---
title: "Survival"
author: "Shelly Trigg"
date: "1/19/2021"
output: html_document
---

1. Load libraries
```{r, load_libraries, echo = FALSE}
library(readxl)
library(plyr)
library(tidyr)
library(ggplot2)
library(FSA)
library(survminer)
library(survival)
library(lme4)
library(lmerTest)
library(knitr)
library(coxme)
library(survMisc)
library(gridExtra)
```



read in data
```{r}
#columns: day, dead, tank, treatment
surv_data <- read_xlsx("../../data/survival/Broodstock_survival_20181112-20190221.xlsx", sheet = "Rdata2")



```



create surv object
```{r}
#make a surv object to pass into coxme

surv <- Surv(time = surv_data$day, event = surv_data$dead, type = "right")

```


```{r}
jpeg("surv_plot.jpg", width = 6, height = 4, units = "in", res = 300)
ggsurvplot(survfit(surv ~ pCO2, surv_data), risk.table = F, pval = F , conf.int = TRUE, palette = alpha(c("#00BFC4", "#F8766D"),c(0.7,0.5)), break.x.by = 10 ,xlab = "days", legend.title = "treatment", legend.labs = c("ambient pCO2 (839 uatm)", "high pCO2 (5430 uatm)"))
dev.off()
```
run cox propotional hazard test
```{r}
survFit1 <- coxph(surv ~ factor(pH), surv_data )
summary(survFit1)
```

include tank as a random effect
```{r}
survFitME <- coxme(surv ~ factor(pH) + (1|tank), surv_data)
summary(survFitME)
#The standard deviation of the tank random effect is very small (0.02) which suggests that tank does not really affect the outcome. Also the liklihood ratio test (Chi?sq) value is the same (15.4), meaning that including tank as a random effect does not improve the model. We likely do not need to include it as a random effect. 
```

calculate coefficient of determination (r^2)
```{r}
rsq(survFit1, sigD=2)


```



```{r}


#pairwise comparisons

library(multcomp)

glht(survFitME, linfct = mcp(pH = "Dunnett"),alternative = "greater")

```
we can conclude that pH had a significant effect on survival given the wald statistic of >